version: '3.7'

services:
    registry:
        image: registry:2
        ports:
            - "5000:5000"
        environment:
                REGISTRY_AUTH: htpasswd
                REGISTRY_AUTH_HTPASSWD_REALM: server
                REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.password
                #REGISTRY_HTTP_ADDR: 0.0.0.0:443
                #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.crt
                #REGISTRY_HTTP_TLS_KEY: /certs/domain.key
            #REGISTRY_HTTP_TLS_CERTIFICATE: /certs/selfsigned.crt
            #REGISTRY_HTTP_TLS_KEY: /certs/selfsigned.key
        volumes:
            - /auth:/auth
                #- /certs:/certs

    python:
        container_name: python
        build:
            context: ./python
            dockerfile: dockerfile
        networks:
            - local

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: dockerfile
        ports:
            - "3000:80"
        networks:
            - local

networks: 
    local:
