version: '3.7'

services:
    python:
        container_name: python
        image: ghcr.io/yarlermanden/discordbot/python:main
        networks:
            - local

    frontend:
        container_name: frontend
        image: ghcr.io/yarlermanden/discordbot/frontend:main
        ports:
            - "3000:80"
        networks:
            - local
        deploy:
            replicas: 4
            update_config:
                parallelism: 1
                delay: 20s
                order: start-first

networks: 
    local:
