version: '3.7'

services:
    python:
        container_name: python
        build:
            context: ./python
            dockerfile: dockerfile
        networks:
            - local

    frontend:
        container_name: frontend
        build:
            context: ./frontend
            dockerfile: dockerfile
        ports:
            - "3000:80"
        networks:
            - local

networks: 
    local:
